chore: tentatively merge into zip file
This is extremely hacky and I'm just using this as workaround until Sonatype clarifies if the Central Publisher API supports tarballs.

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -51,20 +51,28 @@ runs:
           esac
         done
 
-    - name: "Create merged tarball"
+#    - name: "Create merged tarball"
+#      shell: bash
+#      run: |
+#        case "${{ inputs.compression }}" in
+#          gz) COMP="z" ;;
+#          xz) COMP="J" ;;
+#          bz2) COMP="j" ;;
+#          none) COMP="" ;;
+#          *) echo "Invalid compression method"; exit 1 ;;
+#        esac
+#
+#        OUTPUT="${{ inputs.archive }}"
+#        mkdir -p "$(dirname "$OUTPUT")"
+#        tar -c${COMP}f "$OUTPUT" -C "$TMPDIR" .
+
+    # TODO: This should create a tar file, but the Central Portal does not accept tarballs apparently. So, I'm hacking this for now while waiting for Sonatype's support.
+    - name: "Create merged zip"
       shell: bash
       run: |
-        case "${{ inputs.compression }}" in
-          gz) COMP="z" ;;
-          xz) COMP="J" ;;
-          bz2) COMP="j" ;;
-          none) COMP="" ;;
-          *) echo "Invalid compression method"; exit 1 ;;
-        esac
-
         OUTPUT="${{ inputs.archive }}"
         mkdir -p "$(dirname "$OUTPUT")"
-        tar -c${COMP}f "$OUTPUT" -C "$TMPDIR" .
+        (cd "$TMPDIR" && zip -rq "$OUTPUT" .)
 
 branding:
   icon: archive
